import { sql } from "drizzle-orm";
import { pgSequence, pgTable, serial, integer, text, numeric, timestamp, index, boolean, unique } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const ordersTable = pgTable("orders", {
  id: serial("id").primaryKey(),
  // Keep this as text so historical KTP-... references remain readable while
  // new references can be numeric values generated by the database sequence.
  orderNumber: text("order_number").notNull().unique().default(sql`nextval('order_reference_seq')::text`),
  customerId: text("customer_id").notNull(),
  customerName: text("customer_name").notNull(),
  customerEmail: text("customer_email").notNull(),
  customerPhone: text("customer_phone").notNull(),
  idempotencyKey: text("idempotency_key").notNull(),
  currency: text("currency").notNull().default("EGP"),
  subtotal: numeric("subtotal", { precision: 12, scale: 2 }).notNull(),
  discount: numeric("discount", { precision: 12, scale: 2 }).notNull().default("0"),
  total: numeric("total", { precision: 12, scale: 2 }).notNull(),
  promoCode: text("promo_code"),
  paymentMethod: text("payment_method"),
  referralCode: text("referral_code"),
  status: text("status").notNull().default("awaiting_payment"),
  countedAsSold: boolean("counted_as_sold").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (table) => ({
  customerCreatedIdx: index("orders_customer_created_idx").on(table.customerId, table.createdAt),
  statusCreatedIdx: index("orders_status_created_idx").on(table.status, table.createdAt),
  customerIdempotencyKeyUnique: unique("orders_customer_idempotency_key_unique").on(table.customerId, table.idempotencyKey),
}));

export const orderReferenceSequence = pgSequence("order_reference_seq", { startWith: 1000 });

export const orderItemsTable = pgTable("order_items", {
  id: serial("id").primaryKey(),
  orderId: integer("order_id").notNull().references(() => ordersTable.id, { onDelete: "cascade" }),
  productId: integer("product_id").notNull(),
  productName: text("product_name").notNull(),
  coverImageUrl: text("cover_image_url"),
  duration: text("duration").notNull(),
  unitPrice: numeric("unit_price", { precision: 12, scale: 2 }).notNull(),
  quantity: integer("quantity").notNull().default(1),
  lineTotal: numeric("line_total", { precision: 12, scale: 2 }).notNull(),
});

export const analyticsVisitsTable = pgTable("analytics_visits", {
  id: serial("id").primaryKey(),
  visitorId: text("visitor_id").notNull(),
  path: text("path").notNull(),
  productId: integer("product_id"),
  countryCode: text("country_code").notNull().default("UNKNOWN"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  createdIdx: index("analytics_visits_created_idx").on(table.createdAt),
  productCreatedIdx: index("analytics_visits_product_created_idx").on(table.productId, table.createdAt),
  countryCreatedIdx: index("analytics_visits_country_created_idx").on(table.countryCode, table.createdAt),
}));

export const insertOrderSchema = createInsertSchema(ordersTable).omit({ id: true, createdAt: true, updatedAt: true });
export type InsertOrder = z.infer<typeof insertOrderSchema>;
export type Order = typeof ordersTable.$inferSelect;
export type OrderItem = typeof orderItemsTable.$inferSelect;
export type AnalyticsVisit = typeof analyticsVisitsTable.$inferSelect;
